//generated by ResBuilder in 2024-02-03 16:37:11
#ifndef _RESULT_STR_INDEX_H_  
#define _RESULT_STR_INDEX_H_  

////StrResID Define Table////
#define  M26                       1   
#define  M27                       2   

#endif
